version: 2.1

jobs:
  build:

    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install -r requirements.txt
            pip list
            echo "hello word"
      - run: python main.py
#  test:
#
#    docker:
#      - image: "circleci/python:3.7.4"
#    steps:
#      - checkout
#      - run:
#          name: Install Python dependencies
#          command:
#            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
#            pip install -r requirements.txt
#            pip list
#      - run: python3 main.py

workflows:
  build_and_test:
    jobs:
      - build
#      - test:
#          requires:
#            - build